### ISSUE TITLE
Package blacklist

### ISSUE THREAD

**Issue by Panman82** [gcollazo/ember-addons-server#1]
In relation to gcollazo/ember-cli-addon-search#25, create a blacklist option to filter out un-needed packages. Specifically, those with a name starting with "ember-cli-fill-murray-*"

**Comment by gcollazo** [comment]
Thanks for creating the issue. I'll have time to work on this next week :)

**Comment by gcollazo** [comment]
Fixed with e0dabd87869b8c08edff19d16ac91d206b8a7da0
