### ISSUE TITLE
Ember Observer API is changing

### ISSUE THREAD

**Issue by kategengler** [gcollazo/ember-addons-server#2]
We're changing the api to enable new features and help performance. The current endpoint /api/addons that emberaddons uses will no longer include 'note'. The other fields are still available.

**Comment by gcollazo** [comment]
Thanks for the heads up. Will that info be available in another field or is just going away?

**Comment by kategengler** [comment]
It's going away for that part of the api. It'll be in an "extended" form of the addon api but only for single addon requests. I'm making a bunch of changes leading up to moving to JSON API. Hopefully other than the final move to JSON API, this should be the only change that affects emberaddons.

**Comment by gcollazo** [comment]
Cool. Thanks again.

**Comment by kategengler** [comment]
Thanks for the quick response :+1:
