### ISSUE TITLE
Switch to new Ember Observer API

### ISSUE THREAD

**Issue by kategengler** [gcollazo/ember-addons-server#3]
Ember Observer is going to (read: needs to) retire the old api. Some thoughts on moving to our new API:

The new api is at /api/v2 and follows (for most things) JSONAPI convention. In the new api, for performance reasons, we don't allow fetching of all addons at once, the api is paginated. 
To get the scores for all the addons, you'd need to fetch max 100 at a time:
`https://www.emberobserver.com/api/v2/addons?filter[name]=ember-power-select,ember-cli-mirage&fields[addons]=name,score,is-wip&page[limit]=100` with an accept header of `application/vnd.api+json` and filling out the 'name' filter for the hundred addons you want.

I think the above method would be tedious to do server side. I wonder if It might make sense to have the client fetch the scores for each page of addons as they are displayed.

There is one api endpoint that has all addons and isn't paginated that could be used on the server: `https://www.emberobserver.com/api/v2/autocomplete_data`

Which returns a response like (but with all addons): 

```
{
  "addons": [
    {
      "id": 4022,
      "name": "ember-cli-build-config-editor",
      "description": "Utility for ember blueprints to use to modify ember-cli-build.js",
      "score": null,
      "is_wip": false
    },
    {
      "id": 1820,
      "name": "ember-pod-css",
      "description": "The default blueprint for ember-cli addons.",
      "score": 5,
      "is_wip": true
    }
  ]
}
```

Once fetched, any GET to Ember Observer is cached for 1 hour, since that is our update frequency. 

Happy to open a PR but would like to know which direction you'd like to go. I suppose we could also revive our discussions about merging the two sites. 

For anyone following along: Any documentation in this issue should NOT be considered documentation of a public Ember Observer API. Ember Addons is a special case.

**Comment by gcollazo** [comment]
Thanks for the heads up @kategengler. Without giving much thought to it, **if is not an issue on your side of things**, I prefer the `/api/v2/autocomplete_data` option since it's closest to what we have now.

I see that the new api version is already up so I could do the implementation this week.

**Comment by kategengler** [comment]
Not at all a problem to use that endpoint, that's why I described it. The only thing a little weird about it is the naming for this use case. Looking at the code, I _think_ just changing the Ember Observer API URL will do it.

**Comment by gcollazo** [comment]
Completed this today. Along with async/await 😄 . I will test implementing the other changes we talked about today. Thanks for the help @kategengler.
