### ISSUE TITLE
The npm-registry module does'nt work anymore, so the addon list can't be updated

### ISSUE THREAD

**Issue by GerritSommer** [gcollazo/ember-addons-server#4]
This is a follow-up of this issue:
https://github.com/gcollazo/ember-cli-addon-search/issues/105

The npm-registry package is used to load a json list of npm-modules. The npm API seems to have changed and the tool doesn't find any addons anymore.
https://github.com/3rd-Eden/npmjs

I'm testing out if I can replace or udpate that tool.

**Comment by GerritSommer** [comment]
It seems the API to list all npm has been deprecated and is gone.
I am experimenting with: https://github.com/nice-registry/all-the-packages
but I am not sure if the process of parsing ALL npm modules for a keyword takes to much memory. Also there will be a 540MB sized file, for local caching.

I will report my progress.

**Comment by GerritSommer** [comment]
@gcollazo Ok, I think I got.
I didn't do many (or any) PR's to OSS yet, but I will clean up my code and make a PR and then soon the site should be updated again.

**Comment by kategengler** [comment]
EmberObserver.com has switched to using a different API. We've chatted before about emberaddons pulling from EmberObserver.com (discussion here https://github.com/gcollazo/ember-addons-server/issues/3). This might be the time to do that.

**Comment by gcollazo** [comment]
@kategengler I would like to do this but can't find the time 😢
